name: Workflow CI - Wine Quality Model

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  # ============================================================
  # JOB: Train Model with MLflow  (BASIC + SKILLED)
  # ============================================================
  train:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r MLProject/requirements.txt

      - name: Run training with MLflow
        run: |
          cd MLProject
          mlflow run . --env-manager=local
